name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Inject environment variable into HTML
        run: |
          sed -i "s|<!--GPT_TOKEN_PLACEHOLDER-->|<script>const GPT_TOKEN = '${{ secrets.GPT_TOKEN }}';</script>|g" ./index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # 公開するHTMLファイルのディレクトリ
